<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Instructeur;
use AppBundle\Entity\Member;
use Doctrine\ORM\EntityRepository;

/**
 * LessonRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
    /**
     * @return Lesson[]
     */
    public function verkrijgLesAanbodBezoeker()
    {
        $em = $this->getEntityManager();
        $query=$em->createQuery("SELECT d FROM AppBundle:Lesson d WHERE CURRENT_TIMESTAMP() < d.date");
        return $query->getResult();
    }

    /**
     * @return Lesson[]
     */
    public function verkrijgGeregistreerdeLessen(Member $member)
    {
        $em = $this->getEntityManager();
        $query=$em->createQuery("SELECT d FROM AppBundle:Lesson d, AppBundle:Registration r WHERE CURRENT_TIMESTAMP() < d.date AND r.lesson = d AND r.member = :member");
        $query->setParameter('member', $member);
        return $query->getResult();
    }

    /**
     * @return Lesson[]
     */
    public function verkrijgInstructeurLessen(Instructeur $instructeur){
        $em = $this->getEntityManager();
        $query=$em->createQuery("SELECT d FROM AppBundle:Lesson d, AppBundle:Registration r WHERE CURRENT_TIMESTAMP() < d.date AND r.lesson = d AND d.instructeur = :instructeur");
        $query->setParameter('instructeur', $instructeur);
        return $query->getResult();
    }
}
