<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LessonRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
    /**
     * @return Lesson[]
     */
    public function verkrijgLesAanbodBezoeker()
    {
        $em = $this->getEntityManager();
        $query=$em->createQuery("SELECT d FROM AppBundle:Lesson d WHERE CURRENT_TIMESTAMP() < d.date");
        return $query->getResult();
    }
}
